export const NavigationKey = {
    WELCOME: 'Welcome',
    CREATEDUKAN: 'CreateDukan',
    SHOPDETAILS: 'ShopDetails',
    SETPASSWORD: 'SetPassword',
    ADDDUKANMEMBERS: 'AddDukanMembers',
    AUTHNAVIGATOR: 'AuthNavigator',
    VERIFICATION: 'Verification',
    OPENDUKAN: 'OpenDukan',
    BHARATBAZARHOME: 'BharatBazarHome',
    HOME: 'Home',
    PRODUCTDETAILS: 'ProductDetails',
    PRODUCTSUBCATEGORY: 'ProductSubCategory',
    PRODUCTSEARCH: 'ProductSearch',
    PRODUCT: 'Product',
    CREATEPRODUCT: 'CreateProduct',
};
