export const NavigationKey = {
    WELCOME: 'Welcome',
    CREATEDUKAN: 'CreateDukan',
    SHOPDETAILS: 'ShopDetails',
    SETPASSWORD: 'SetPassword',
    ADDDUKANMEMBERS: 'AddDukanMembers',
    AUTHNAVIGATOR: 'AuthNavigator',
    VERIFICATION: 'Verification',
    OPENDUKAN: 'OpenDukan',
    BHARATBAZARHOME: 'BharatBazarHome',
    HOME: 'Home',
    PRODUCTDETAILS: 'ProductDetails',
    PRODUCTSUBCATEGORY: 'ProductSubCategory',
    PRODUCTSEARCH: 'ProductSearch',
    PRODUCT: 'Product',
    CREATEPRODUCT: 'CreateProduct',
    PRODUCTCATEGORY: 'ProductCategory',
    ADDRESS: 'Address',
    SPLASH: 'SplashScreen',
    FORGETPASSWORD: 'ForgetPassword',
    VERIFYOTP: 'VerifyOTP',
    RESETPASSWORD: 'ResetPassword',
    PRODUCTSTATUS: 'ProductStatus',
    EDITDUKANMEMBER: 'EditDukanMember',
    EditProductSize: 'EditProductSize',
    SELECTFILTER: 'SelectFilter',
    CREATEBILL: 'CreateBill',
};
